/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'doctorNotes' : string,
  'status' : AppointmentStatus,
  'doctorId' : Principal,
  'patientId' : Principal,
  'date' : string,
  'timeSlot' : string,
  'reason' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Hospital {
  'id' : string,
  'city' : string,
  'name' : string,
  'address' : string,
  'hospitalType' : string,
  'phone' : string,
}
export interface MedicalHistory {
  'id' : string,
  'title' : string,
  'patientId' : Principal,
  'date' : string,
  'description' : string,
  'blobId' : [] | [string],
  'category' : string,
}
export interface Medicine {
  'dosage' : string,
  'frequency' : string,
  'medicineName' : string,
}
export interface MedicineReminder {
  'id' : string,
  'active' : boolean,
  'endDate' : string,
  'dosage' : string,
  'patientId' : Principal,
  'frequency' : string,
  'startDate' : string,
  'medicineName' : string,
}
export interface Message {
  'id' : string,
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'isRead' : boolean,
  'timestamp' : bigint,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'notifType' : string,
  'body' : string,
  'userId' : Principal,
  'isRead' : boolean,
  'timestamp' : bigint,
}
export interface Prescription {
  'id' : string,
  'doctorId' : Principal,
  'dateIssued' : string,
  'patientId' : Principal,
  'notes' : string,
  'blobId' : string,
  'medicineList' : Array<Medicine>,
}
export interface SymptomCheckerInput {
  'age' : [] | [bigint],
  'gender' : [] | [string],
  'symptoms' : Array<string>,
}
export interface SymptomCheckerResult {
  'relatedConditions' : Array<string>,
  'recommendedAction' : string,
  'disclaimer' : string,
  'severityHint' : string,
}
export interface SymptomQuery {
  'result' : SymptomCheckerResult,
  'patientId' : Principal,
  'timestamp' : bigint,
  'input' : SymptomCheckerInput,
}
export interface SystemStats {
  'totalPatients' : bigint,
  'totalPrescriptions' : bigint,
  'totalDoctors' : bigint,
  'totalUsers' : bigint,
  'totalAppointments' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'languagePreference' : string,
  'name' : string,
  'role' : UserRole,
  'largeTextMode' : boolean,
  'specialty' : [] | [string],
  'consentDataSharing' : boolean,
  'rating' : number,
  'reviewCount' : bigint,
  'verificationStatus' : VerificationStatus,
}
export type UserRole = { 'patient' : null } |
  { 'admin' : null } |
  { 'doctor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicalHistoryEntry' : ActorMethod<
    [string, string, string, string, [] | [string]],
    string
  >,
  'addMedicineReminder' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'approveDoctor' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelAppointment' : ActorMethod<[string], undefined>,
  'checkSymptoms' : ActorMethod<[SymptomCheckerInput], SymptomCheckerResult>,
  'completeAppointment' : ActorMethod<[string, string], undefined>,
  'confirmAppointment' : ActorMethod<[string], undefined>,
  'createAppointment' : ActorMethod<
    [Principal, string, string, string],
    string
  >,
  'createNotification' : ActorMethod<
    [Principal, string, string, string],
    string
  >,
  'createPrescription' : ActorMethod<
    [Principal, string, string, string, Array<Medicine>],
    string
  >,
  'getAppointmentsForUser' : ActorMethod<[Principal], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getHospitalsByCity' : ActorMethod<[string], Array<Hospital>>,
  'getMedicalHistoryForPatient' : ActorMethod<
    [Principal],
    Array<MedicalHistory>
  >,
  'getNotificationsForUser' : ActorMethod<[Principal], Array<Notification>>,
  'getPrescriptionsForPatient' : ActorMethod<[Principal], Array<Prescription>>,
  'getRemindersForPatient' : ActorMethod<[Principal], Array<MedicineReminder>>,
  'getSymptomQueryLog' : ActorMethod<[Principal], Array<SymptomQuery>>,
  'getSystemStats' : ActorMethod<[], SystemStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageRead' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'rejectDoctor' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], string>,
  'updateReminderActiveStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];