/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SymptomCheckerInput = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'gender' : IDL.Opt(IDL.Text),
  'symptoms' : IDL.Vec(IDL.Text),
});
export const SymptomCheckerResult = IDL.Record({
  'relatedConditions' : IDL.Vec(IDL.Text),
  'recommendedAction' : IDL.Text,
  'disclaimer' : IDL.Text,
  'severityHint' : IDL.Text,
});
export const Medicine = IDL.Record({
  'dosage' : IDL.Text,
  'frequency' : IDL.Text,
  'medicineName' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'doctorNotes' : IDL.Text,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Principal,
  'date' : IDL.Text,
  'timeSlot' : IDL.Text,
  'reason' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'languagePreference' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'largeTextMode' : IDL.Bool,
  'specialty' : IDL.Opt(IDL.Text),
  'consentDataSharing' : IDL.Bool,
  'rating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'verificationStatus' : VerificationStatus,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'hospitalType' : IDL.Text,
  'phone' : IDL.Text,
});
export const MedicalHistory = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'patientId' : IDL.Principal,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'blobId' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notifType' : IDL.Text,
  'body' : IDL.Text,
  'userId' : IDL.Principal,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Prescription = IDL.Record({
  'id' : IDL.Text,
  'doctorId' : IDL.Principal,
  'dateIssued' : IDL.Text,
  'patientId' : IDL.Principal,
  'notes' : IDL.Text,
  'blobId' : IDL.Text,
  'medicineList' : IDL.Vec(Medicine),
});
export const MedicineReminder = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'endDate' : IDL.Text,
  'dosage' : IDL.Text,
  'patientId' : IDL.Principal,
  'frequency' : IDL.Text,
  'startDate' : IDL.Text,
  'medicineName' : IDL.Text,
});
export const SymptomQuery = IDL.Record({
  'result' : SymptomCheckerResult,
  'patientId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'input' : SymptomCheckerInput,
});
export const SystemStats = IDL.Record({
  'totalPatients' : IDL.Nat,
  'totalPrescriptions' : IDL.Nat,
  'totalDoctors' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalAppointments' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicalHistoryEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'addMedicineReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'approveDoctor' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelAppointment' : IDL.Func([IDL.Text], [], []),
  'checkSymptoms' : IDL.Func([SymptomCheckerInput], [SymptomCheckerResult], []),
  'completeAppointment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'confirmAppointment' : IDL.Func([IDL.Text], [], []),
  'createAppointment' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPrescription' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Medicine)],
      [IDL.Text],
      [],
    ),
  'getAppointmentsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getHospitalsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Hospital)], ['query']),
  'getMedicalHistoryForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MedicalHistory)],
      ['query'],
    ),
  'getNotificationsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPrescriptionsForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getRemindersForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MedicineReminder)],
      ['query'],
    ),
  'getSymptomQueryLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SymptomQuery)],
      ['query'],
    ),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageRead' : IDL.Func([IDL.Text], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'rejectDoctor' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'updateReminderActiveStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SymptomCheckerInput = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'gender' : IDL.Opt(IDL.Text),
    'symptoms' : IDL.Vec(IDL.Text),
  });
  const SymptomCheckerResult = IDL.Record({
    'relatedConditions' : IDL.Vec(IDL.Text),
    'recommendedAction' : IDL.Text,
    'disclaimer' : IDL.Text,
    'severityHint' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'dosage' : IDL.Text,
    'frequency' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'doctorNotes' : IDL.Text,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Principal,
    'date' : IDL.Text,
    'timeSlot' : IDL.Text,
    'reason' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'languagePreference' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'largeTextMode' : IDL.Bool,
    'specialty' : IDL.Opt(IDL.Text),
    'consentDataSharing' : IDL.Bool,
    'rating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'verificationStatus' : VerificationStatus,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'hospitalType' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MedicalHistory = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'patientId' : IDL.Principal,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'blobId' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notifType' : IDL.Text,
    'body' : IDL.Text,
    'userId' : IDL.Principal,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Text,
    'doctorId' : IDL.Principal,
    'dateIssued' : IDL.Text,
    'patientId' : IDL.Principal,
    'notes' : IDL.Text,
    'blobId' : IDL.Text,
    'medicineList' : IDL.Vec(Medicine),
  });
  const MedicineReminder = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'endDate' : IDL.Text,
    'dosage' : IDL.Text,
    'patientId' : IDL.Principal,
    'frequency' : IDL.Text,
    'startDate' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  const SymptomQuery = IDL.Record({
    'result' : SymptomCheckerResult,
    'patientId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'input' : SymptomCheckerInput,
  });
  const SystemStats = IDL.Record({
    'totalPatients' : IDL.Nat,
    'totalPrescriptions' : IDL.Nat,
    'totalDoctors' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalAppointments' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicalHistoryEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'addMedicineReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'approveDoctor' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelAppointment' : IDL.Func([IDL.Text], [], []),
    'checkSymptoms' : IDL.Func(
        [SymptomCheckerInput],
        [SymptomCheckerResult],
        [],
      ),
    'completeAppointment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'confirmAppointment' : IDL.Func([IDL.Text], [], []),
    'createAppointment' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPrescription' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Medicine)],
        [IDL.Text],
        [],
      ),
    'getAppointmentsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getHospitalsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Hospital)], ['query']),
    'getMedicalHistoryForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MedicalHistory)],
        ['query'],
      ),
    'getNotificationsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPrescriptionsForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getRemindersForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MedicineReminder)],
        ['query'],
      ),
    'getSymptomQueryLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SymptomQuery)],
        ['query'],
      ),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageRead' : IDL.Func([IDL.Text], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'rejectDoctor' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'updateReminderActiveStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };