/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SymptomCheckerResult {
    relatedConditions: Array<string>;
    recommendedAction: string;
    disclaimer: string;
    severityHint: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SystemStats {
    totalPatients: bigint;
    totalPrescriptions: bigint;
    totalDoctors: bigint;
    totalUsers: bigint;
    totalAppointments: bigint;
}
export interface SymptomQuery {
    result: SymptomCheckerResult;
    patientId: Principal;
    timestamp: bigint;
    input: SymptomCheckerInput;
}
export interface MedicalHistory {
    id: string;
    title: string;
    patientId: Principal;
    date: string;
    description: string;
    blobId?: string;
    category: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Notification {
    id: string;
    title: string;
    notifType: string;
    body: string;
    userId: Principal;
    isRead: boolean;
    timestamp: bigint;
}
export interface Hospital {
    id: string;
    city: string;
    name: string;
    address: string;
    hospitalType: string;
    phone: string;
}
export interface Message {
    id: string;
    to: Principal;
    content: string;
    from: Principal;
    isRead: boolean;
    timestamp: bigint;
}
export interface MedicineReminder {
    id: string;
    active: boolean;
    endDate: string;
    dosage: string;
    patientId: Principal;
    frequency: string;
    startDate: string;
    medicineName: string;
}
export interface Medicine {
    dosage: string;
    frequency: string;
    medicineName: string;
}
export interface SymptomCheckerInput {
    age?: bigint;
    gender?: string;
    symptoms: Array<string>;
}
export interface Prescription {
    id: string;
    doctorId: Principal;
    dateIssued: string;
    patientId: Principal;
    notes: string;
    blobId: string;
    medicineList: Array<Medicine>;
}
export interface Appointment {
    id: string;
    doctorNotes: string;
    status: AppointmentStatus;
    doctorId: Principal;
    patientId: Principal;
    date: string;
    timeSlot: string;
    reason: string;
}
export interface UserProfile {
    id: Principal;
    bio: string;
    languagePreference: string;
    name: string;
    role: UserRole;
    largeTextMode: boolean;
    specialty?: string;
    consentDataSharing: boolean;
    rating: number;
    reviewCount: bigint;
    verificationStatus: VerificationStatus;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    patient = "patient",
    admin = "admin",
    doctor = "doctor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMedicalHistoryEntry(title: string, description: string, date: string, category: string, blobId: string | null): Promise<string>;
    addMedicineReminder(medicineName: string, dosage: string, frequency: string, startDate: string, endDate: string): Promise<string>;
    approveDoctor(doctorId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelAppointment(appointmentId: string): Promise<void>;
    checkSymptoms(input: SymptomCheckerInput): Promise<SymptomCheckerResult>;
    completeAppointment(appointmentId: string, doctorNotes: string): Promise<void>;
    confirmAppointment(appointmentId: string): Promise<void>;
    createAppointment(doctorId: Principal, date: string, timeSlot: string, reason: string): Promise<string>;
    createNotification(userId: Principal, title: string, body: string, notifType: string): Promise<string>;
    createPrescription(patientId: Principal, blobId: string, notes: string, dateIssued: string, medicineList: Array<Medicine>): Promise<string>;
    getAppointmentsForUser(userId: Principal): Promise<Array<Appointment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getConversation(otherUser: Principal): Promise<Array<Message>>;
    getHospitalsByCity(city: string): Promise<Array<Hospital>>;
    getMedicalHistoryForPatient(patientId: Principal): Promise<Array<MedicalHistory>>;
    getNotificationsForUser(userId: Principal): Promise<Array<Notification>>;
    getPrescriptionsForPatient(patientId: Principal): Promise<Array<Prescription>>;
    getRemindersForPatient(patientId: Principal): Promise<Array<MedicineReminder>>;
    getSymptomQueryLog(patientId: Principal): Promise<Array<SymptomQuery>>;
    getSystemStats(): Promise<SystemStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markMessageRead(messageId: string): Promise<void>;
    markNotificationRead(notificationId: string): Promise<void>;
    rejectDoctor(doctorId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(to: Principal, content: string): Promise<string>;
    updateReminderActiveStatus(reminderId: string, active: boolean): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, MedicalHistory as _MedicalHistory, SymptomCheckerInput as _SymptomCheckerInput, SymptomCheckerResult as _SymptomCheckerResult, SymptomQuery as _SymptomQuery, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, VerificationStatus as _VerificationStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMedicalHistoryEntry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicalHistoryEntry(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicalHistoryEntry(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addMedicineReminder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicineReminder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicineReminder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async approveDoctor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDoctor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async checkSymptoms(arg0: SymptomCheckerInput): Promise<SymptomCheckerResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSymptoms(to_candid_SymptomCheckerInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSymptoms(to_candid_SymptomCheckerInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async completeAppointment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeAppointment(arg0, arg1);
            return result;
        }
    }
    async confirmAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAppointment(arg0);
            return result;
        }
    }
    async createAppointment(arg0: Principal, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createNotification(arg0: Principal, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPrescription(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: Array<Medicine>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAppointmentsForUser(arg0: Principal): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsForUser(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsForUser(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getHospitalsByCity(arg0: string): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalsByCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalsByCity(arg0);
            return result;
        }
    }
    async getMedicalHistoryForPatient(arg0: Principal): Promise<Array<MedicalHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalHistoryForPatient(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalHistoryForPatient(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsForUser(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForUser(arg0);
            return result;
        }
    }
    async getPrescriptionsForPatient(arg0: Principal): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsForPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsForPatient(arg0);
            return result;
        }
    }
    async getRemindersForPatient(arg0: Principal): Promise<Array<MedicineReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemindersForPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemindersForPatient(arg0);
            return result;
        }
    }
    async getSymptomQueryLog(arg0: Principal): Promise<Array<SymptomQuery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSymptomQueryLog(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSymptomQueryLog(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStats(): Promise<SystemStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessageRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async rejectDoctor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDoctor(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateReminderActiveStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminderActiveStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminderActiveStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MedicalHistory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicalHistory): MedicalHistory {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SymptomCheckerInput_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SymptomCheckerInput): SymptomCheckerInput {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SymptomQuery_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SymptomQuery): SymptomQuery {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    doctorNotes: string;
    status: _AppointmentStatus;
    doctorId: Principal;
    patientId: Principal;
    date: string;
    timeSlot: string;
    reason: string;
}): {
    id: string;
    doctorNotes: string;
    status: AppointmentStatus;
    doctorId: Principal;
    patientId: Principal;
    date: string;
    timeSlot: string;
    reason: string;
} {
    return {
        id: value.id,
        doctorNotes: value.doctorNotes,
        status: from_candid_AppointmentStatus_n16(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        timeSlot: value.timeSlot,
        reason: value.reason
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    languagePreference: string;
    name: string;
    role: _UserRole;
    largeTextMode: boolean;
    specialty: [] | [string];
    consentDataSharing: boolean;
    rating: number;
    reviewCount: bigint;
    verificationStatus: _VerificationStatus;
}): {
    id: Principal;
    bio: string;
    languagePreference: string;
    name: string;
    role: UserRole;
    largeTextMode: boolean;
    specialty?: string;
    consentDataSharing: boolean;
    rating: number;
    reviewCount: bigint;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        bio: value.bio,
        languagePreference: value.languagePreference,
        name: value.name,
        role: from_candid_UserRole_n21(_uploadFile, _downloadFile, value.role),
        largeTextMode: value.largeTextMode,
        specialty: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.specialty)),
        consentDataSharing: value.consentDataSharing,
        rating: value.rating,
        reviewCount: value.reviewCount,
        verificationStatus: from_candid_VerificationStatus_n24(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    patientId: Principal;
    date: string;
    description: string;
    blobId: [] | [string];
    category: string;
}): {
    id: string;
    title: string;
    patientId: Principal;
    date: string;
    description: string;
    blobId?: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        patientId: value.patientId,
        date: value.date,
        description: value.description,
        blobId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.blobId)),
        category: value.category
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _SymptomCheckerResult;
    patientId: Principal;
    timestamp: bigint;
    input: _SymptomCheckerInput;
}): {
    result: SymptomCheckerResult;
    patientId: Principal;
    timestamp: bigint;
    input: SymptomCheckerInput;
} {
    return {
        result: value.result,
        patientId: value.patientId,
        timestamp: value.timestamp,
        input: from_candid_SymptomCheckerInput_n34(_uploadFile, _downloadFile, value.input)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    gender: [] | [string];
    symptoms: Array<string>;
}): {
    age?: bigint;
    gender?: string;
    symptoms: Array<string>;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        gender: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.gender)),
        symptoms: value.symptoms
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
}): UserRole {
    return "patient" in value ? UserRole.patient : "admin" in value ? UserRole.admin : "doctor" in value ? UserRole.doctor : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): VerificationStatus {
    return "pending" in value ? VerificationStatus.pending : "approved" in value ? VerificationStatus.approved : "rejected" in value ? VerificationStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicalHistory>): Array<MedicalHistory> {
    return value.map((x)=>from_candid_MedicalHistory_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SymptomQuery>): Array<SymptomQuery> {
    return value.map((x)=>from_candid_SymptomQuery_n32(_uploadFile, _downloadFile, x));
}
function to_candid_SymptomCheckerInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SymptomCheckerInput): _SymptomCheckerInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    gender?: string;
    symptoms: Array<string>;
}): {
    age: [] | [bigint];
    gender: [] | [string];
    symptoms: Array<string>;
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        symptoms: value.symptoms
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    languagePreference: string;
    name: string;
    role: UserRole;
    largeTextMode: boolean;
    specialty?: string;
    consentDataSharing: boolean;
    rating: number;
    reviewCount: bigint;
    verificationStatus: VerificationStatus;
}): {
    id: Principal;
    bio: string;
    languagePreference: string;
    name: string;
    role: _UserRole;
    largeTextMode: boolean;
    specialty: [] | [string];
    consentDataSharing: boolean;
    rating: number;
    reviewCount: bigint;
    verificationStatus: _VerificationStatus;
} {
    return {
        id: value.id,
        bio: value.bio,
        languagePreference: value.languagePreference,
        name: value.name,
        role: to_candid_UserRole_n38(_uploadFile, _downloadFile, value.role),
        largeTextMode: value.largeTextMode,
        specialty: value.specialty ? candid_some(value.specialty) : candid_none(),
        consentDataSharing: value.consentDataSharing,
        rating: value.rating,
        reviewCount: value.reviewCount,
        verificationStatus: to_candid_VerificationStatus_n40(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
} {
    return value == UserRole.patient ? {
        patient: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.doctor ? {
        doctor: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == VerificationStatus.pending ? {
        pending: null
    } : value == VerificationStatus.approved ? {
        approved: null
    } : value == VerificationStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
